### ISSUE TITLE
Change browser language

### ISSUE THREAD

**Issue by budetisufu** [intika/Librefox#103]
Hey. What settings are responsible for the browser language? As for me, the configuration file is badly commented. This is confusing.

**Comment by intika** [comment]
Hi, if you mean the interface your Firefox needs to be in the language you want before applying Librefox... or you can install a language pack of your choice 

Firefox language version: https://www.mozilla.org/en-US/firefox/all/

Language packs: https://addons.mozilla.org/en-US/firefox/language-tools/

**Comment by intika** [comment]
https://github.com/intika/Librefox/pull/104 fixed this... 
You could remove "lockPref("intl.locale.requested", "en-US");" from the `mozilla.cfg` that should help 
i added this to https://github.com/intika/Librefox/issues/3 for further investigation... its not a hasty closure ;)

**Comment by budetisufu** [comment]
This does not solve the problem. The language did not change after installing librefox over firefxox, installed from the repositories.

**Comment by bogachenko** [comment]
@budetisufu you have commented out `lockPref("intl.locale.requested", "en-US");` in file mozilla.cfg? or not? Restart your browser. Once you comment out this parameter, the value is reset to an empty string.
![default](https://user-images.githubusercontent.com/8535285/51724202-2749cb00-2054-11e9-80e6-d5ed2eb3080a.png)
 download the language pack from the site mozilla.org. and then manually type the locale you need.
I'm from Russia, so I have ru
![2](https://user-images.githubusercontent.com/8535285/51724211-32046000-2054-11e9-9be2-15761c3cad6e.png)


EZ

**Comment by budetisufu** [comment]
Of course commented out. I don't need to download anything. Everything is already in the system. Downloaded from the Mozilla site has no problems.

**Comment by intika** [comment]
@budetisufu a couple of question to be able to help you the right way: 
- Without Librefox, is you firefox install in the language you want ? 
- Do you have the language pack installed ? (about:addons then language pack)
- `lockPref("intl.locale.requested", "en-US")` is meant for the displayed webpage not for the interface... i though this affected the interface
- What's the language you want to use ? 
- What distro do you use ?

Eventually i'll send back the needed language pack xpi over here

**Comment by bogachenko** [comment]
he downloaded the already translated version

**Comment by intika** [comment]
@bogachenko thank you for helping out on this one :)... wait and see what's his answer it's not clear

**Comment by intika** [comment]
i think i found the problem...

**Comment by bogachenko** [comment]
> 
> 
> i think i found the problem...

?

**Comment by intika** [comment]
First thing first the add button when installing language package does not work because of resistFingerprinting feature that spoof the wrong Firefox's version to the Mozilla's addons site... and other telemetry settings that disable Mozilla's site from using infos about the browser 

@budetisufu Here is a detailed solution  

1. Check that you have the language pack of the desired language installed under `about:addons` then language.

2. To install a language pack select the needed one from here  https://addons.mozilla.org/en-US/firefox/language-tools/ then you need to select the proper version let say you want the Russian language pack, you will need to download the right version by going into the versions page https://addons.mozilla.org/en-US/firefox/addon/russian-ru-language-pack/versions/ (if you use firefox 64 select the latest v64) right click on the "add to firefox" and select copy link then past it on the url bar and add the language pack 

3. Once the language pack installed you need to check some settings 
- `intl.locale.requested` needs to be emply or referring the the language you want to use like `ru-RU`

4. Other related settings needs to be updated
- `privacy.spoof_english` needs to be set to 1
- `intl.accept_languages` needs to have your language listed for example `ru, ru-ru, en-us, en`

5. You can change settings on 4 with the interface under Preferences/General/Language/Choose and then adding your language to the list... 

Firefox/Librefox should be fine in your language after doing this....

I will see how i can change that behavior on future version... but @bogachenko solution should be just fine. 

Let me know if you need further assistance ;)

**Comment by budetisufu** [comment]
Now everything works! Thank you very much!
