### ISSUE TITLE
Build system as aseperate project

### ISSUE THREAD

**Issue by elypter** [intika/Librefox#107]
could you release the future toolchain used to build up to date version as a seperate project? this will keep the librefox repo compact and allow others to reprpose it for other software and contribute without having to deal with the details of the browser but focus on the task of automatically keeping forked software up to date.

**Comment by intika** [comment]
In an other repo i don't know yet but for sure i will keep things separated i am working on the new version and it's crazy that you posted that today because i was thinking early about splitting Librefox Browser and Librefox mozilla.cfg... but on the repo side thing not the application it self... any way short answer yes it's planned :)

**Comment by intika** [comment]
don't hesitate to let me know if there is something else ;)
