### ISSUE TITLE
Add a wiki page

### ISSUE THREAD

**Issue by shreyasminocha** [intika/Librefox#111]
Could we move documentation for the rules in `mozilla.cfg` out of the file and instead use either `docs/rules` with markdown files or Github's wiki feature (I personally prefer the former)? This would make going through the rules much easier. Permalinking to a certain Librefox-modified rule's documentation would be easier. Scrolling through the `mozilla.cfg` when you're looking for something specific would be easier. It would be easy to later use the markdown docs to generate html docs for use on the website. Besides separation of concerns is usually a good thing anyway.

I could work on this if approved.

Edit: Here's an example — https://gist.github.com/shreyasminocha/d197ce3f4a8c7bc6ecdf64d34d121f37

**Comment by intika** [comment]
Thanks you Shreyas, 

- Removing the documentation from `mozilla.cfg` is not a good idea as we would need to check the wiki plus `mozilla.cfg` when we want to edit/change something this would make the development of the cfg file consume more time. 

- Having additional/copied documentations in a github's wiki page is good idea, **but** i think this would be counterproductive if we fill that wiki with all the values, because user/devs willing to make changes would just find the important info directly on the cfg file. 

- Thus said, a wiki page with most important settings (not all) like cookies/resistFingerprinting/TLS etc. would be amazing ! ... i am thinking of the settings that were questioned on the closed issues like: https://github.com/intika/Librefox/issues/106 https://github.com/intika/Librefox/issues/103 https://github.com/intika/Librefox/issues/98 https://github.com/intika/Librefox/issues/97 https://github.com/intika/Librefox/issues/85

The idea here is to keep the focus on important things that would make the project as less time consuming as possible, maintaining a wiki page could become a huge work if you have to add documentation about more than 1000 settings, and i even did mention the updates it needs over time...

**So short answer:**

- A wiki ? yes sure that would be amazing
- What would be the content ? 
-- Answer to important questions already asked and answered (closed issues)  
-- Some important cfg settings (not more than 50) like cookies etc. 
-- May be a list of privacy settings that break something.

Any way in the main readme page there are already some wiki sections, if we just add some question/answer on the github wiki that would be enough for the current situation. 

Let me know what you are planning to do :)

**Comment by intika** [comment]
initial wiki introduced here https://github.com/intika/Librefox/wiki i will update/add content later on, a task for it is added here https://github.com/intika/Librefox/issues/3 ;)
