### ISSUE TITLE
Firefox account feature

### ISSUE THREAD

**Issue by dimqua** [intika/Librefox#30]
The Firefox Account feature is disabled, could you explain why?

**Comment by dimqua** [comment]
You can enable this feature, but it doesn't work with the current `mozilla.cfg`.

**Comment by John3** [comment]
> 
> 
> The Firefox Account feature is disabled, could you explain why?

If we are talking about privacy, you can replaced with some other solution or you can run you own sync server https://github.com/mozilla-services/syncserver

**Comment by dimqua** [comment]
> you can replaced with some other solution

Could anyone recommend something?

**Comment by John3** [comment]
> > you can replaced with some other solution
> 
> Could anyone recommend something?

Yes sure here is one https://www.xbrowsersync.org/

**Comment by drkui** [comment]
Personally, I would like to have Mozilla sync my bookmarks, since I'm using a temporary email for the sync anyway. It would be nice to enable the feature optionally for people that want it.

@dimqua I would recommend using the extension Floccus for handling bookmarks. It's open source and uses Nextcloud/Webdav. The only unfortunate part is that since the bookmark API isn't implemented for Firefox for Android, so you can't use Floccus on your phone yet. Which is why I'm using Mozilla sync just for bookmarks in the first place.

**Comment by intika** [comment]
Syncing feature is by design not compatible with a privacy enforced browser. 
Now i agree that the user should always have the choice. 
For the moment this feature is not compatible with the feature "Zero unneeded connection" 
I am planning to add an advanced settings page in the Firefox settings page i will see how i can integrate a switch for the sync feature, but this (if it is doable/compatible with the rest) will be added after the development of the settings page and main features... 
So i will keep this open until it's time to look at it.
