### ISSUE TITLE
Custom Fake Useragent

### ISSUE THREAD

**Issue by tuzohetoruyu** [intika/Librefox#90]
i fear the point where a exploit is found in ff, while it is fixed in the common version
librefox will continue be available as target. with that i mind i would prefer so fake the
useragent to another browser engine (safri,opera,chrome) and auto disable javascript functions which are only available in firefox engines. so exploits cant detect what real browser engine ur using,
best would be to fake/implement custom javascript code from other engines.

Also please publish the build instruction.
So far love ur project, great work!

**Comment by intika** [comment]
Thank you very much for you feedback :)

Current/Old build instruction can be found here https://github.com/intika/Librefox/tree/9f8b1260e486ffc2fe8a0bb267108f71773c72a3#building-and-packaging i will add other build instruction once v3 will be published... currently it's not needed because the project is just a set of config files

**Comment by intika** [comment]
Let me know if you need further infos ;)

**Comment by intika** [comment]
For the Useragent settings i think it's better to leave the choice to the user because of RFP and other related things

**Comment by tuzohetoruyu** [comment]
okay yeah maybe ur right about this, but how frequently will be security updates applied. i mean one
day could be to late. i'm looking forward developing a ff addon for these purpose.  Ty for the build info

**Comment by intika** [comment]
There is always 0day un leaked exploit... if you disable JS you should be good in most situations
