### ISSUE TITLE
problems with Google recaptcha

### ISSUE THREAD

**Issue by Brotherlui** [intika/Librefox#97]
Hi, i really would like to thank you providing us enhanced security with Librefox.
After installing, i´ve got problems with Googles reCAPTCHAs not working properly anymore.
Solved puzzles are not recognized anymore, switching to audio results in a statement
"Your computer or network may send automated requests. For the protection of our users, we are currently unable to process your request. More information can be found on our help pages".
Maybe there are settings i need to change? Who can help?
Many thanks in advance.

**Comment by intika** [comment]
Thank you for your feedback, this is a duplicate of the issue https://github.com/intika/Librefox/issues/89
indeed this is a side effect of privacy, this is because of cookies most of the time, for example the Google Captcha which is used widely will let you in without verification if you are logged into your google account or if it detect other activities like amazon etc. (over cookies), there is no magic solution if you want less authentication bot you will need to enable cookie and keep them over restart. (disable sanitizing cookie when the browser is closed) but bear in mind that this lead to tracking which is used to identify you as not being a bot...

here is what to do to stay connected on sites and avoid bot check :

1. Comment `lockPref("network.cookie.lifetimePolicy", 2) ` by adding `//` at the beginning of the line under the file `mozilla.cfg`

2. Open Firefox's preferences, under "Privacy & Security" (about:preferences#privacy) right to `Clear history when Firefox closes` click `Settings...` and uncheck `Cookies` and `Active Logins `

**Comment by intika** [comment]
Let me know if you need further help ;)
